# Generated by Django 3.1.5 on 2021-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
