# Generated by Django 3.1.5 on 2021-04-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_student_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='propic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.FileField(upload_to='profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.logindetails')),
            ],
        ),
    ]
