# Generated by Django 3.1.5 on 2021-04-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_propic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propic',
            old_name='propic',
            new_name='propicture',
        ),
    ]
